export * as schema from './schema';
export { createDatabase, getDb, type Database, type DatabaseHandle, type Executor } from './client';
export { loadEnv, requireEnv, REPO_ROOT } from './env';
export { runMigrations, dropAll } from './migrate';
export * as catalog from './queries/catalog';
export * as community from './queries/community';
export * as compatQueries from './queries/compat';
export * as mutations from './queries/mutations';
export { CommunityError } from './queries/mutations';
export * as identity from './identity';
export * as jobs from './jobs';
export * from './writers';
export { refreshSearchText } from './search-text';
export { visibleTo, publicAggregateEligible } from './visibility';
export { seedDatabase, FIXTURE_SOURCE_KEY } from './seed';
